spring:
  application:
    name: nailyProject

  profiles:
    include: key

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: be1.2026.nail
    password: ENC(QGfOaj4g41cWhTK+pS/xBw/0oa2MvAFzlDSf+AiNirQ=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 300000
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/naily_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(vu8GQP2qjD0N+lr4aSjGHw==)

  jpa:
    hibernate:
      ddl-auto: update #원래 있던 건 삭제 후 새로운 걸 넣음 (추후 update로 바꾸기)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ENC(uAYjhPVuUKuxBjz3YEDgK/rxu5UtXbipxkgsDq7rCR2XYZg1U9hS2jxX+oK5PIX+)
  expiration: 86400000 #24시간

gemini:
  api:
    key: ENC(f11Gu+eqSDV89d4XdLuuhSgUpmthWA1ZFzmg9oZgvPOmNwjRqrbNyVa5n0uOHLqb)
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"


cloud:
  aws:
    credentials:
      access-key: ENC(jRZOYDKW6O+5etRT6PeZCVhUzethhP2zK+KNAqo5OIU=)
      secret-key: ENC(5yvNDJbbm6948H0BdfBNy+G8tVX0SZY8gNsrS7JwDxbcpzqREoje0Sq5s2bYqEaekmVf+1WHhzY=)
    s3:
      bucket: naily-scans #버킷이름
    region:
      static: us-east-1
    stack:
      auto: false

python:
  server:
    url: http://localhost:8000
